version: '3.8'

services:
  app:
    build:
      context: ./docker/app
    container_name: app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  node:
    image: node:18
    container_name: node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - 5173:5173
    networks:
      - laravel
    tty: true

networks:
  laravel:

volumes:
  db-data: